export const SET_FINANCE_MASTER_DATA = 'SET_FINANCE_MASTER_DATA'
export const SET_ON_ROAD_SHOW ='SET_ON_ROAD_SHOW'
export const SET_FINANCE_CUSTOMER_PHONE = 'SET_FINANCE_CUSTOMER_PHONE' 
export const SET_FINANCE_REQUEST_NUMBER='SET_FINANCE_REQUEST_NUMBER'