export const searchState = {
  searchMasterData: [],
  brand: [],
  categoryType: null,
  feature: [],
  bikeColor: [],
  maxPrice: null,
  minPrice: null,
  minEngineCC: null,
  maxEngineCC: null,
  active: "1",
  modelResData: [],
  sortBy: "Price-asc",
  loading: false,
  clearAll: false,
  fuelType: "Petrol",
  pageSize: 10,
  searchText: "",
};
