export const testRideState = {
    isSubmitted:false,
    isOtpVerified:false,
    isDealerSumbit:false,
    currentPage: "bikeSelect",
    bikeBrand: "",
    bikeVariant: "",
    testRideType: null,
    testRideLocation: null,
    pinCode: null,
    dealerCode: null,
    dealerLoading: false,
    testRideDate: null,
    testRideTime: null,
    testRideSelectedDate: null,
    testRideAddress: null,
    customerFirstName: null,
    customerLastName: null,
    customerEmail: null,
    customerPhone: null,
    drivingLicenceNo: null,
    customerAlternatePhone: null,
    customerPincode: null,
    preSelected: false,
    searchDealersBy:"",
    requestNo: "",
    rideState:"",
    rideCity:"",
}